springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    #please create a secret containing the user password and set the PGPASSFILE env variable in the docker compose file
    # https://www.postgresql.org/docs/current/libpq-pgpass.html
    # https://docs.docker.com/compose/use-secrets/
  sql:
    init:
      mode: none
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      #TODO: using flyway or liquibase would be a better choice...

---
spring:
  config:
    activate:
      on-profile: memdb
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update